version: '3'

services:
  vod_db:
    image: mysql:5.7
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/share/docker/mysql/mysql:/var/lib/mysql"
      - "/home/share/docker/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: 123
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    restart: always
    ports:
      - 3306:3306
    networks:
      - webnet

  vod:
    depends_on:
      - vod_db
    image: vod:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - /home/share/vod/media:/app/media    #path of upload media
      - /home/share/vod/record:/app/record  #path of record media
      - /home/share/vod/static:/app/static
      - /media/tongshi:/media/tongshi
    environment:
      DJANGO_DB_HOST: vod_db
      TSRTMP_DB_HOST: vod_db
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "3"
    restart: always
    ports:
      - 8000:8000
    networks:
      - webnet

networks:
  webnet:
